FROM python:3.9-slim

WORKDIR /app
ENV PYTHONPATH /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Expose the port the app runs on
EXPOSE 8080

# The command to run the application. Flask will automatically find the app
# specified in .flaskenv and run in development mode on all network interfaces.
CMD ["flask", "run", "--host=0.0.0.0","--port=8080"]