services:
  backend:
    container_name: Tucil2-IF4020-backend
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.flaskenv
    restart: always

  frontend:
    container_name: Tucil2-IF4020-frontend
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always
    stdin_open: true
    tty: true
