services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app # Mounts your local backend code into the container for live updates
    env_file:
      - ./backend/.flaskenv
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app # Mounts local frontend code
      - /app/node_modules # Prevents local node_modules from overwriting the container's
    depends_on:
      - backend
    restart: always
    # The following are often needed for Create React App hot-reloading
    stdin_open: true
    tty: true
