services:
  backend:
    container_name: Tucil2-IF4020-backend
    build:
      context: .                # IMPORTANT: context is project root so we can COPY backend/* in Dockerfile
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app                  # hot reload backend code
      - ./vendor/mp3lsbstego:/vendor/mp3lsbstego  # mount vendored lib (private)
    env_file:
      - ./backend/.flaskenv
    restart: always

  frontend:
    container_name: Tucil2-IF4020-frontend
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    environment:
      - VITE_API_BASE=http://localhost:8080     # Frontend → Backend over compose network
      - CHOKIDAR_USEPOLLING=true              # optional: better file watching in containers
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app         # hot reload frontend
      - /app/node_modules       # keep node_modules in container
    depends_on:
      - backend
    restart: always
    stdin_open: true
    tty: true
